name: Semgrep Secrets Scan
on:
  pull_request:

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Run Semgrep
        env:
          SEMGREP_RULES: p/secrets
          SEMGREP_SEND_METRICS: off
        run: |
          semgrep ci \
            --junit-xml \
            -o reports/semgrep.xml
      - name: Publish results
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'reports/semgrep.xml'
          annotate_only: true
